### ISSUE TITLE
Minor typo in an English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marinaglancy/moodle-mod_recommend#2]
Hi Marina,

While I was translating this new plugin, I found a minor typo in one of the English language strings:

 error_requestnotfound | recommend

Sorry we could not find this recommendation requst

'requst' should be 'request' (I think).

Thanks in advance for your help.

**Comment by marinaglancy** [comment]
Thank you, I have added commit with the fix, will release when there is something else
