### ISSUE TITLE
Field "recommendid" does not exist in table "recommend_question"

### ISSUE THREAD

**Issue by ewallah** [marinaglancy/moodle-mod_recommend#3]
Debug info: 
Error code: ddlfieldnotexist
×Stack trace:
line 628 of /lib/dml/moodle_database.php: dml_exception thrown
line 1306 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 83 of /mod/recommend/classes/questions_manager.php: call to moodle_database->get_records()
line 83 of /mod/recommend/classes/recommend_form.php: call to mod_recommend_questions_manager->get_questions()
line 201 of /lib/formslib.php: call to mod_recommend_recommend_form->definition()
line 65 of /mod/recommend/classes/recommend_form.php: call to moodleform->__construct()
line 98 of /mod/recommend/edit.php: call to mod_recommend_recommend_form->__construct()

As a result backup of course fails too...

**Comment by marinaglancy** [comment]
hm, this is very weird, it is there, see https://github.com/marinaglancy/moodle-mod_recommend/blob/master/db/install.xml#L34
Did you by any chance download this plugin before it was added to plugins directory? If so, can you uninstall and install plugin?

**Comment by ewallah** [comment]
Indeed, this plugin was installed before it was added to the plugins directory. A simple reinstall solved the problem.   Sorry for the trouble caused.

**Comment by marinaglancy** [comment]
I guess it's my fault, I removed all upgrade scripts when uploading to the plugins directory - I did not expect anybody was using it directly from my repo
